version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tankgame-db
    environment:
      POSTGRES_DB: tankgame
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11
    command: -url=jdbc:postgresql://postgres:5432/tankgame -user=postgres -password=password -connectRetries=10 migrate
    depends_on:
      - postgres
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  postgres_data:
