package game.input;

public enum InputEventType {
    MOVE_UP_PRESSED,
    MOVE_DOWN_PRESSED,
    MOVE_LEFT_PRESSED,
    MOVE_RIGHT_PRESSED,
    FIRE_PRESSED,
    MOVE_UP_RELEASED,
    MOVE_DOWN_RELEASED,
    MOVE_LEFT_RELEASED,
    MOVE_RIGHT_RELEASED,
    FIRE_RELEASED,
    ESCAPE
}
